name: green_farm_app
description: A comprehensive farming app with plant disease detection for farmers.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Essential packages
  shared_preferences: ^2.2.2
  camera: ^0.10.5+5

  # Voice recognition
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
