// File generated by FlutterFire CLI.
// This is a template file. Run 'flutterfire configure' to generate actual values.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace these with your actual Firebase configuration
  // Run 'flutterfire configure' to generate these values automatically

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhOm_3P8UaJytwa_OJkTxBWqxoiITMer4',
    appId: '1:134716946611:web:74418a649cdce9339bd8c6',
    messagingSenderId: '134716946611',
    projectId: 'greendot-a2731',
    authDomain: 'greendot-a2731.firebaseapp.com',
    storageBucket: 'greendot-a2731.firebasestorage.app',
  );

  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK5sc2RQ1VxBd6dhrNcyjZ2uhBcpFQlnI',
    appId: '1:134716946611:android:826bea6e5ab812379bd8c6',
    messagingSenderId: '134716946611',
    projectId: 'greendot-a2731',
    databaseURL: 'https://greendot-a2731-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greendot-a2731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCNPRbFhi4yFR29X4p39PiS98Z9GoBWyM',
    appId: '1:134716946611:ios:0969a10779e1b9ae9bd8c6',
    messagingSenderId: '134716946611',
    projectId: 'greendot-a2731',
    storageBucket: 'greendot-a2731.firebasestorage.app',
    iosBundleId: 'com.example.greenDot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCNPRbFhi4yFR29X4p39PiS98Z9GoBWyM',
    appId: '1:134716946611:ios:0969a10779e1b9ae9bd8c6',
    messagingSenderId: '134716946611',
    projectId: 'greendot-a2731',
    storageBucket: 'greendot-a2731.firebasestorage.app',
    iosBundleId: 'com.example.greenDot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhOm_3P8UaJytwa_OJkTxBWqxoiITMer4',
    appId: '1:134716946611:web:1a6445463079424e9bd8c6',
    messagingSenderId: '134716946611',
    projectId: 'greendot-a2731',
    authDomain: 'greendot-a2731.firebaseapp.com',
    storageBucket: 'greendot-a2731.firebasestorage.app',
  );

}