// File generated by FlutterFire CLI.
// This is a template file. Run 'flutterfire configure' to generate actual values.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // IMPORTANT: This file has been sanitized for public sharing.
  // The original Firebase configuration values (API keys, App IDs,
  // project IDs, etc.) have been removed to avoid leaking sensitive
  // information. To run the app locally, regenerate this file by
  // running the FlutterFire CLI or provide your own `FirebaseOptions`.
  //
  // Recommended options:
  // 1) Run `flutterfire configure` in this repo to recreate this file.
  // 2) OR create a new file `lib/firebase_options_private.dart` that
  //    provides `DefaultFirebaseOptions.currentPlatform` and import it
  //    from `main.dart` during local development (do NOT commit it).
  //
  // If you accidentally rely on real keys committed here, rotate them
  // in the Firebase console immediately.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: 'REDACTED',
    messagingSenderId: 'REDACTED',
    projectId: 'REDACTED',
    authDomain: 'REDACTED',
    storageBucket: 'REDACTED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: 'REDACTED',
    messagingSenderId: 'REDACTED',
    projectId: 'REDACTED',
    databaseURL: 'REDACTED',
    storageBucket: 'REDACTED',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: 'REDACTED',
    messagingSenderId: 'REDACTED',
    projectId: 'REDACTED',
    storageBucket: 'REDACTED',
    iosBundleId: 'REDACTED',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: 'REDACTED',
    messagingSenderId: 'REDACTED',
    projectId: 'REDACTED',
    storageBucket: 'REDACTED',
    iosBundleId: 'REDACTED',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REDACTED',
    appId: 'REDACTED',
    messagingSenderId: 'REDACTED',
    projectId: 'REDACTED',
    authDomain: 'REDACTED',
    storageBucket: 'REDACTED',
  );

}